baseurl = "http://blog.slabnet.com/"
languageCode = "en-us"
title = "Hugo's Blog"
copyright = "&copy; 2017 Hugo Slabbert. <a href=\"http://creativecommons.org/licenses/by/4.0/\">Some rights reserved</a>. Please attribute properly and link back."

theme = "hucore"

disqusShortname = "blog-slabnet-com"

[taxonomies]
    # Optional. Use if you want tags and lists.
    category = "categories"
    tag = "tags"
    topic = "topics"

#[author]
#    name = "Hugo Slabbert"
#    email = "hugo@slabnet.com"

[indexes]
  tags = "tags"

[[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 0
    identifier = "home"
    url = "/"
[[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 1
    identifier = "post"
    url = "/post/"
[[menu.main]]
    name = "Tags"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 2
    identifier = "tags"
    url = "/tags/"
[[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 3
    identifier = "about"
    url = "/about/"
[[menu.main]]
    name = "Disclaimer"
    url = "/disclaimer"
    weight = 4

[params]
    brand = "Hugo's Blog"
    description = "Mostly tech...mostly"
    subtitle = "Mostly tech...mostly"
    author = "Hugo"

    # Sidebar position
    # false, true, "left", "right"
    sidebar = "left"

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    #highlight = "default"

    twitter_username = "hugoslabbert"
    disqus = "blog-slabnet-com"
    disqus_shortname = "blog-slabnet-com"
    sharingicons = true
    keywords = ["tech", "networking"]

[params.highlight]
style = "solarized-dark"
languages = ["bash", "go", "dockerfile", "python", "powershell"]

[[params.social]]
url = "https://github.com/hslabbert"
fa_icon = "fa-github"

[[params.social]]
url = "https://gitlab.com/hslabbert"
fa_icon = "fa-gitlab"

[[params.social]]
url = "https://twitter.com/hugoslabbert"
fa_icon = "fa-twitter"

[[params.social]]
url = "https://linkedin.com/in/hugoslabbert"
fa_icon = "fa-linkedin-square"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"

[[params.socialshare]]
url = "https://linkedin.com/in/hslabbert"
fa_icon = "fa-linkedin-square"

[social]
    # Link your social networking accouns to the side menu
    # by entering your username or ID.

    # SNS microblogging
    twitter = "hugoslabbert"
    googleplus = "HugoSlabbert-B178313E"

    linkedin = "hugoslabbert"
    github = "hslabbert"
    reddit = "BitterOleNetworkOp"
