baseurl = "http://blog.slabnet.com/"
languageCode = "en-us"
title = "Hugo's Blog"
copyright = "&copy; 2016 Hugo Slabbert. <a href=\"http://creativecommons.org/licenses/by/4.0/\">Some rights reserved</a>. Please attribute properly and link back."

theme = "blackburn"

paginate = 10
paginatePath = "page"

[taxonomies]
    # Optional. Use if you want tags and lists.
    category = "categories"
    tag = "tags"
    topic = "topics"

[author]
    name = "Hugo Slabbert"
    email = "hugo@slabnet.com"

[[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 0
    identifier = "home"
    url = "/"
[[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 1
    identifier = "post"
    url = "/post/"
[[menu.main]]
    name = "Tags"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 2
    identifier = "tags"
    url = "/tags/"
[[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 3
    identifier = "about"
    url = "/about/"
[[menu.main]]
    name = "Disclaimer"
    url = "/disclaimer"
    weight = 4

[params]
    brand = "Hugo's Blog"
    description = "Mostly tech...mostly"
    subtitle = "Mostly tech...mostly"

    # Sidebar position
    # false, true, "left", "right"
    sidebar = "left"

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "default"

    disqus = "blog-slabnet-com"

[social]
    # Link your social networking accouns to the side menu
    # by entering your username or ID.

    # SNS microblogging
    twitter = "hugoslabbert"
    googleplus = "HugoSlabbert-B178313E"

    linkedin = "hugoslabbert"
    github = "hslabbert"
    reddit = "BitterOleNetworkOp"
